
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 09 23:15:29 CET 2021
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 38;
  public static final int CONST = 3;
  public static final int GE = 14;
  public static final int SEMI = 20;
  public static final int LROUND = 27;
  public static final int RROUND = 28;
  public static final int LT = 15;
  public static final int BOOL = 37;
  public static final int QMARK = 21;
  public static final int COMMA = 23;
  public static final int INC = 18;
  public static final int DIV = 9;
  public static final int NUM = 35;
  public static final int ASSIGN = 17;
  public static final int LE = 16;
  public static final int EOF = 0;
  public static final int RETURN = 32;
  public static final int TRUE = 33;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int MUL = 8;
  public static final int LCURLY = 25;
  public static final int ADD = 6;
  public static final int MOD = 10;
  public static final int IDENT = 36;
  public static final int VOID = 31;
  public static final int EQ = 11;
  public static final int RCURLY = 26;
  public static final int COLON = 22;
  public static final int LSQUARE = 29;
  public static final int READ = 5;
  public static final int RSQUARE = 30;
  public static final int PROG = 2;
  public static final int NE = 12;
  public static final int DEC = 19;
  public static final int FALSE = 34;
  public static final int GT = 13;
  public static final int SUB = 7;
  public static final int PRINT = 4;
}

